[properties]
AWS_ACCESS_KEY_ID:placeholder
AWS_SECRET_ACCESS_KEY:placeholder
BUCKET_NAME:placeholder
INPUT_FILE_PATH:Input/input_gds.csv
OUTPUT_PATH:cm-report/
LOCAL_PATH:/root/data/
REGION:us-east-1
